# Google App Engine deployment configuration
# Basketball Analysis Service - Production deployment

runtime: python311

# Instance configuration - optimized for basketball analysis workload
instance_class: F4_1G
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation for video processing
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

# Environment variables - optimized for production
env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: false
  TF_CPP_MIN_LOG_LEVEL: '2'
  MEDIAPIPE_DISABLE_GPU: '1'
  OPENCV_DISABLE_CUDA_CACHE: '1'
  MAX_PROCESSING_TIME: '300'
  MAX_CONCURRENT_JOBS: '2'
  FRAME_SKIP: '2'
  GARBAGE_COLLECTION_INTERVAL: '10'
  PYTHONUNBUFFERED: '1'
  SECRET_KEY: your-super-secret-basketball-key-change-this-to-something-random

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 15
  failure_threshold: 3
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 15
  failure_threshold: 3
  success_threshold: 2

# Network and service configuration
inbound_services:
- warmup

# Handlers for static files and API
handlers:
- url: /static
  static_dir: static
  secure: always
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /.*
  script: auto
  secure: always

# Files are now ignored via .gcloudignore file for Python 3.11 runtime
