# Google Cloud App Engine Configuration
# Basketball Analysis Service v9.0 - Production Ready

runtime: python311
service: default
instance_class: F4_1G

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables for production
env_variables:
  FLASK_ENV: "production"
  FLASK_DEBUG: "False"
  TF_CPP_MIN_LOG_LEVEL: "2"
  MEDIAPIPE_DISABLE_GPU: "1"
  ENABLE_SHOULDER_ALIGNMENT_DETECTION: "True"
  KNEE_BEND_THRESHOLD: "130"
  MAX_VIDEO_SIZE_MB: "100"
  FRONTEND_URL: "https://apexsports-llc.com"

# Handlers for static files and application
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Resource limits
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
