#!/bin/bash
# Basketball Analysis Service - Instant Deployment Commands
# Copy and paste these commands to deploy your service

echo "🚀 Basketball Analysis Service - Instant Deployment"
echo "=================================================="
echo ""
echo "Step 1: SSH into your server"
echo "Run this command (replace 'your_username' with your actual username):"
echo ""
echo "ssh your_username@apexsports-llc.com"
echo ""
echo "Step 2: Once connected to your server, run the deployment script:"
echo ""
echo "curl -sSL https://raw.githubusercontent.com/rickdyer20/apex-sports-trainer/working-full-featured/deploy_from_git.sh | bash"
echo ""
echo "Step 3: After deployment completes, start your service:"
echo ""
echo "cd apex-sports-trainer"
echo "gunicorn -w 4 -b 0.0.0.0:80 complete_web_app:app"
echo ""
echo "🎉 Your Basketball Analysis Service will be live!"
echo "Visit: https://apexsports-llc.com"
echo ""
echo "💰 Revenue Model Active:"
echo "  🆓 Free: 1 analysis per year"
echo "  💵 One-time: \$9.99 for 5 analyses"
echo "  🔥 Pro: \$19.99/month unlimited"
echo "  🌟 Enterprise: \$49.99/month premium"
echo ""
echo "🔐 Live Stripe Integration: Ready for real payments!"
