#!/bin/bash
# Custom Domain Setup for apexsports-llc.com
# Map your Namecheap domain to Google Cloud

echo "🌐 Setting up custom domain: apexsports-llc.com"
echo "=============================================="

# Add custom domain mapping
echo "📋 Adding domain mapping..."
gcloud app domain-mappings create apexsports-llc.com --quiet

echo ""
echo "🎯 DOMAIN SETUP COMPLETE!"
echo ""
echo "📝 DNS CONFIGURATION REQUIRED:"
echo "   1. Login to Namecheap"
echo "   2. Go to Domain List > Manage apexsports-llc.com"
echo "   3. Advanced DNS > Add these records:"
echo ""
echo "   📍 CNAME Record:"
echo "      Host: www"
echo "      Value: ghs.googlehosted.com"
echo "      TTL: Automatic"
echo ""
echo "   📍 A Record:"
echo "      Host: @"
echo "      Value: 216.239.32.21"
echo "      TTL: Automatic"
echo ""
echo "   📍 A Record:"
echo "      Host: @"  
echo "      Value: 216.239.34.21"
echo "      TTL: Automatic"
echo ""
echo "   📍 A Record:"
echo "      Host: @"
echo "      Value: 216.239.36.21"
echo "      TTL: Automatic"
echo ""
echo "   📍 A Record:"
echo "      Host: @"
echo "      Value: 216.239.38.21"
echo "      TTL: Automatic"
echo ""
echo "⏰ DNS propagation takes 24-48 hours"
echo ""
echo "🎉 Once complete, your Basketball Analysis Service will be live at:"
echo "   https://apexsports-llc.com"
echo "   https://www.apexsports-llc.com"
echo ""
echo "💰 START GENERATING REVENUE IMMEDIATELY!"
